version: '3.7'
services:
    web:
        image: docker-flask
        build: .
        command: flask run
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
    mongodb:
        image: "mongo"
        ports:
            - "27017:27017"